Erfahrene Hebamme bietet Mitarbeit an
Sehr geehrter Herr Peters,
man sagt, dass Essen den Körper, Wissenschaft den Geist und Liebe die Seele nährt.
Diese Zusammenhänge spielen eine wichtige Rolle bei der Geburt und im weiteren Leben. Daher sind sie
mir ein Leitbild.
Ich bin ausgebildete Hebamme assistierte den Hebammen und Ärzt*innen während der Ausbildung (Level 1)
bei über 300 Geburten.
In diesem Rahmen konnte ich zudem viel Erfahrung im Umgang mit Geburtskomplikationen sammeln.
Selbst bei schwierigen Geburten bleibe ich stets ruhig. Diese Ruhe strahlt auf die werdenden Mütter aus.
Bereits frühzeitig war ich für die tägliche medizinische Grundversorgung verantwortlich, wie die Messung
der Vitalzeichen und die Untersuchung der ungeborenen Babys.
Ich habe mir Ihre Stellanzeige angesehen und konnte mir dadurch einen guten Eindruck verschaffen. Ich
könnte mir vorstellen, Sie zu unterstützen, und deshalb bewerbe ich mich bei Ihnen.
Ich arbeite flexibel, konzentriert, liebevoll und fleißig, zukunftsorientiert und verantwortungsvoll. Mit
Herz, mit Blick für das Ganze und mit der Bereitschaft, Verantwortung zu übernehmen. Gleichzeitig
bringe ich die nötige emotionale Intelligenz mit, um mich gut in Teams einzufügen und im Arbeitsalltag
Stabilität zu geben.
Wenn ich Ihr Interesse geweckt haben sollte, würde ich mich über eine Einladung zu einem persönlichen
Gespräch freuen.
Mit freundlichen Grüßen
Bekime Elezi

LEBENSLAUF
PERSÖNLICHES
* 30.04.1976 in Gostivar, Mazedonien
geschieden

us-amerikanisch

BERUFLICHER WERDEGANG
Seit 05.2025 Individuelles Bewerbungscoaching
Zug um Zug gGmbH, Köln

10/2024 – 04.2025 arbeitssuchend
09/2020 – 09/2024 Hebammenhelferin, St. Marien Hospital, Düren

09/2018 – 09/2019 Pflegehelferin, Evangelisches Krankenhaus, Kalk 09/2017 –
08/2018 Pflegehelferin, Promedis24
02/2016 – 07/2017 Bürohilfe, Wolpert GmbH u. Co. KG, Köln
● Telefonzentrale
● Kundengespräche
● Reinigung der Büroräume
● Allgemeine Büroarbeiten

09/2015 – 02/2016 Produktionshelferin, Marta Iwona Hahn Verpackungstechnik, Leverkusen 10/2015
Sprachschule INTEGRA, Köln – Deutsch Level B2 09/2015 Deutschsprachkurs, Köln
06/2015 Auswanderung in die Bundesrepublik Deutschland und Arbeitsaufnahme
12/2014 – 04/2015 Arzthelferin und Verwaltungsmitarbeiterin
Dr. Dereye Ayo, Burleson,Texas / USA

05/2009 – 05/2015 Pflegehilfe in der Onkologie

Huguley Hospital, Fort Worth, Burleson,Texas / USA
06/2007 – 04/2009 Restaurantbesitzerin, Daily Special Cafe, Alvarado, Texas / USA
09/2003 – 05/2007 Aushilfe im familieneigenen Restaurant in Mazedonien während des Studiums
11/2000 – 08/2003 Hausfrau, Umzug nach Texas, Eltern- und Familienzeit 10/1998 –
08/1999 Hausfrau Eltern- und Familienzeit

11/1997 Auswanderung: Vereinigten Staaten von Amerika, Neuorientierung, Sprachkurs
03/1996 – 07/1997 Zahnarzthelferin, Dendia Estetico, Gostivar / Mazedonien

SCHUL- UND AUSBILDUNG
05/1998 – 09/1998 Englischsprachkurs, Sprachschule in New Jersey
07/2013 – 04/2015 Studium der Krankenpflege, University of Texas, Arlington / USA Abschluss:

Bachelor in Nursing
09/2003 – 05/2007 Studium der Biologie, Nebenfach Biochemie
McMurry University, Abilene, Texas / USA
Abschluss: Bachelor Biologie
09/1999 – 09/2000 Bergen Community College New Jersey/USA
08/ 1995 – 02/1996 Praktikum als Krankenschwester

General Hospital Gostivar, Gostivar, Mazedonien

09/1991 – 06/1995 Ausbildung als Hebamme, Medizinische Hochschule Nikola Stein Tetovo /
Mazedonien - Abschluss: Staatlich geprüfte Hebamme
09/1982 – 06/1991 Grund- und Mittelschule Mosha Pijade, Gostivar, Mazedonien Abschluss:

Mittlere Reife

FÄHIGKEITEN UND INTERESSEN
Sprachen: Deutsch – C1

Englisch – fließend
Albanisch – Muttersprache

Bekime Elezi
Köln, 21. Juli 2025